### ISSUE TITLE
failed on training example

### ISSUE THREAD

**Issue by shcup** [amzn/amazon-dsstne#106]
I try to run the example with the commad "train -c config.json -i gl_input.nc -o gl_output.nc -n gl.nc -b 256 -e 10" and then, I met some problems. After the commad, I got some messege like this 

Train will use configuration file: config.json
Train will use input data file: gl_input.nc
Train will use output data file: gl_output.nc
Train will produce networkFileName: gl.nc
Train will use batchSize: 256
Train will use number of epochs: 10
Train alpha 0.025, lambda 0.0001, mu 0.5.Please check CDL.txt for meanings
GpuContext::Startup: Process 0 out of 1 initialized.
cudaGetDeviceCount failed CUDA driver version is insufficient for CUDA runtime version
train: GpuTypes.cpp:95: void GpuContext::Startup(int, char**): Assertion `0' failed.
[ubuntu:25037] *** Process received signal ***
[ubuntu:25037] Signal: Aborted (6)
[ubuntu:25037] Signal code:  (-6)

is there really something matter with CUDA driver version? Must I use GPU  or can I use CPU instead. 
thank you

**Comment by tristanpenman** [comment]
The DSSTNE engine, and the 'predict' and 'train' utilities all require an NVIDIA GPU to run.

Can you paste the output of running `nvidia-smi` on your system, and provide some additional information such as which OS/distribution you're using?

**Comment by ekandrotA9** [comment]
This looks to be a driver issue rather than a DSSTNE issue.  I'm recommending that it be closed, because it has been a year with no new info.
