### ISSUE TITLE
Running on 1 GPU and on 4 GPU gives different results provided the same input

### ISSUE THREAD

**Issue by eddiesun** [amzn/amazon-dsstne#123]
I followed this example without a word changed. https://github.com/amznlabs/amazon-dsstne/blob/master/docs/getting_started/examples.md

First I run it on a **g2.2xlarge** instance with a single GPU. The result looks good. Different users got recommended (mostly) different movies.

Then I run it on a **g2.8xlarge** instance with 4 GPUs. The only difference is I ran this command for training `mpirun -np 4 train -c config.json -i gl_input.nc -o gl_output.nc -n gl.nc -b 256 -e 10` which is the exact command shown in the examples.md file.
Again, same data, same command, same everything, except `mpirun -np 4 train xxxx` vs `train xxxx`...

The output result from the 4-GPU instance is completely different than the single GPU case. In the 4-GPU case, almost every user got recommended movie id 592 as first (or first a few) recommendation. It looks much worse than the 1 GPU case.

I suspect there is a bug with multi-GPU case? Or is this expected?

Thanks,
Eddie

**Comment by scottlegrand** [comment]
I don't have access to the data as I'm no longer an employee, but that is
distressing. I'm not surprised that there is a difference in the results
but if there is a qualitative difference in the results that is a problem.
It's not possible to make the results reproducible without rewriting the
Cuda math libraries. The determinism guarantee only applies to be running
on exactly the same architecture.

 Any differences you see should be no worse than rerunning with a different
random seed on a single GPU.

**Comment by ekandrotA9** [comment]
There was a patch a month or two ago, because the sizes of the files changed based on the number of GPUs.  That was fixed.  It might have been the cause of your problem as well.  Please let me know if latest Master fixes it for you, thanks.
