### ISSUE TITLE
Possible to get output from an "internal" layer?

### ISSUE THREAD

**Issue by JDRomano2** [amzn/amazon-dsstne#129]
I'm working on building an autoencoder model, and need to be able to "pull out" the data we pass in at different stages of propagating through the trained network. For example, if the network layers are arranged like this:
`I --> H1 --> H2 --> H3 --> H4 --> H5 --> O`,
then I want to run `predict` and see what the data look like in layer `H3` as well as their final representation in layer `O`.

The documentation seems to suggest that this might be possible using features already built into dsstne, but I can't figure it out. Does this have something to do with the "target" layers that are mentioned in `docs/getting_started/LDL.txt`?

**Comment by slegrandA9** [comment]
You can get a pointer to a layer by name with:
const NNLayer* NNNetwork::GetLayer(const string& layer) const

You can get the size of a layer's buffer and its activations and deltas with:
    NNFloat* GetUnitBuffer() { return _pbUnit ? _pbUnit->_pDevData : NULL; }
    NNFloat* GetDeltaBuffer() { return _pbDelta ? _pbDelta->_pDevData : NULL; }
    uint64_t GetBufferSize() { return _batch * _stride; }

**Comment by slegrandA9** [comment]
Closing issue, question answered
