### ISSUE TITLE
Issue: cannot find —Icudnn *** [generateNetCDF]

### ISSUE THREAD

**Issue by reachviji** [amzn/amazon-dsstne#133]
When I run the Build code:
export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
make

I get the following error:
/usr/bin/ Id: cannot find —Icudnn
collect2: error: Id returned 1 exit status
a ke [1): *** [generateNetCDF] Error 1
a ke [1) : Leaving directory / home/ubuntu/amazon—dsstne/src/amazon/dsstne/utils'
ake: [bin/train) Error 2

How to resolve this?

**Comment by scottlegrand** [comment]
Get cuDNN and install it in your CUDA directory.

**Comment by reachviji** [comment]
I have downloaded cuDNN from link
https://developer.nvidia.com/rdp/cudnn-download
cuDNN v6.0 Library for Linux
 and cuDNN v6.0 Library for Windows 10
and saved the same in CUDA directory under amazon-dsstne folder.
Still facing the issue.

**Comment by reachviji** [comment]
![image](https://user-images.githubusercontent.com/29367204/27252713-b6213e44-5382-11e7-90b8-4777bb85ad08.png)

**Comment by reachviji** [comment]
Resolved the issue,

**Comment by slegrandA9** [comment]
Closing
