### ISSUE TITLE
Explain the recs file for DSSTNE predict

### ISSUE THREAD

**Issue by nimit2894** [amzn/amazon-dsstne#136]
Hello,
I am new to DSSTNE, so I am unable to understand what is the output generated by DSSTNE. The recs file gives 10 recommendations for each user in the following format

userID movieID,number between 0-1: movieID,number between 0-1

What is this number between 0-1 that is given here?

**Comment by scottlegrand** [comment]
It's the output of a sigmoid unit and ranges from 0 to 1 with higher being
a more likely recommendation.

**Comment by nimit2894** [comment]
Thank you very much for the clarification.
I am completely unfamiliar with C++, so is there any efficient implementation of the DSSTNE algorithm in an environment like R or Python?

**Comment by scottlegrand** [comment]
A python interface is on the roadmap, likely a Keras interface.

**Comment by ekandrotA9** [comment]
There doesn't appear to be an issue here, any future APIs or interfaces should be on the roadmap.
