### ISSUE TITLE
final "make" of setup // cuda.h: there is no such a file or directory

### ISSUE THREAD

**Issue by altairlight** [amzn/amazon-dsstne#151]
~$ export PATH=/usr/local/openmpi/bin:/usr/local/cuda/bin:$PATH
~$ cd amazon-dsstne/src/amazon/dsstne/
~/amazon-dsstne/src/amazon/dsstne$ ls
Makefile  Makefile.inc  engine  utils
~/amazon-dsstne/src/amazon/dsstne$ make
cd engine && make
make[1]: 디렉터리 '/home/altairlight/amazon-dsstne/src/amazon/dsstne/engine' 들어감
************  RELEASE mode ************
mpiCC -DOMPI_SKIP_MPICXX -std=c++0x -O3 -I/usr/local/cuda/include -IB40C -IB40C/KernelCommon -I/usr/local/include -I/usr/lib/openmpi/include -I/usr/include/jsoncpp -I../utils -I../engine -I/usr/include/cppunit -c NNTypes.cpp
In file included from NNTypes.cpp:13:0:
GpuTypes.h:20:18: fatal error: cuda.h: 그런 파일이나 디렉터리가 없습니다
compilation terminated.
Makefile:37: 'NNTypes.o' 타겟에 대한 명령이 실패했습니다
make[1]: *** [NNTypes.o] 오류 1
make[1]: 디렉터리 '/home/altairlight/amazon-dsstne/src/amazon/dsstne/engine' 나감
Makefile:13: 'lib/libdsstne.a' 타겟에 대한 명령이 실패했습니다
make: *** [lib/libdsstne.a] 오류 2

Umm.. I can find cuda.h in /usr/include/hwloc$ and /usr/include/linux$ but I really cannot get it this error. help me please.

**Comment by ekandrotA9** [comment]
Have you installed cuDNN?  It is in the Docker, but has to be installed by hand in you install your own

**Comment by altairlight** [comment]
It still has same error..

**Comment by scottlegrand** [comment]
Where did you put the cudnn files?

**Comment by altairlight** [comment]
/home
I found that It seems to be put at usr/local/cuda but I dont have this folder
Should I have to install CUDA?

**Comment by scottlegrand** [comment]
Yes you have to install the Cuda toolkit first and then cudnn within it.
That this is too independent steps is really doofy on the part of Nvidia
but that's the way it is.
