### ISSUE TITLE
movielens predicting timestamp?

### ISSUE THREAD

**Issue by bkj** [amzn/amazon-dsstne#175]
In the `samples/movielens` example, it looks like we're predicting the timestamp -- is that right?  Seems like a more typical example would be predicting the ratings? 

```
$ head ml-20m_ratings.csv
userId,movieId,rating,timestamp
1,2,3.5,1112486027
1,29,3.5,1112484676
1,32,3.5,1112484819
1,47,3.5,1112484727
1,50,3.5,1112484580

$ head -n 1 ml-20m_rating
1	2,1112486027:29,1112484676:32,1112484819:47,1112484727:50

```

~ Ben

**Comment by scottlegrand** [comment]
This is meant to recommend movies the viewer is likely to watch next.
Hence you want it to be a function of both rating and timing.  Hence we use
the recent viewing history of the crowd as a basis for predicting what's
next.

Predicting ratings alone would have it recommend any movie the viewer is
likely to enjoy.

Predicting what's popular alone would only recommend the top movies being
viewed, which is a decent coldstart, but we can and have done much better
than that.

Scott

**Comment by bkj** [comment]
OK -- makes sense I think.  Thanks!
