### ISSUE TITLE
Compilation Fail on Ubuntu 16.04 64 bit

### ISSUE THREAD

**Issue by sarvex** [amzn/amazon-dsstne#28]
r/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

Getting this compilation error while compiling destiny on Ubuntu 16.04 64 bit

**Comment by scottlegrand** [comment]
On Thu, May 26, 2016 at 4:54 AM, Sarvex Jatasra <notifications@github.com>
wrote:

> __builtin_ia32_monitorx



TensorFlow has seen this as well.

Try adding:

+  cxx_flag: "-D_MWAITXINTRIN_H_INCLUDED"+  cxx_flag: "-D__STRICT_ANSI__"

Context:
https://github.com/tensorflow/tensorflow/issues/1066

**Comment by sarvex** [comment]
@scottlegrand 
Thanks for the link, i have seen the same link and was waiting for "nvidia best practices" because google deferred the answer. 

If this is the recommended practice by DSSTNE, either the documentation or the code should be updated to save the newcomers from failing builds.

**Comment by ekandrotA9** [comment]
This appears to be a bug in CUDA 7.5 with a compiler version it doesn't support.  This is no longer true, since CUDA 8, and with the current CUDA 9.  At this point, I'm assuming this isn't an issue and closing it.  Please feel free to undo that if it is still a problem with the correct compiler/CUDA pairings.

**Comment by AOphagen** [comment]
Just encountered the error message again with CUDA 9.0, Ubuntu 16.04, C++11, GCC, NVCC. Thankfully the workaround of @scottlegrand is still working. Please don't mind the haphazard look of the included `CMakeList.txt`, I just wanted to check something quickly with a piece of code.

```
# CMakeLists.txt
cmake_minimum_required(VERSION 2.8)
project( placement_new )

set( CUDA_TOOLKIT_ROOT_DIR "/Developer/NVIDIA/CUDA-9.0/")
find_package(CUDA QUIET REQUIRED)

set( ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR})
set( SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)

set( CUDA_SOURCES
     ${SRC_DIR}/main.cu
)
set( CPP_SOURCES
     ${SRC_DIR}/primitive.h
     ${SRC_DIR}/arena.cpp
)

IF (WIN32)
ELSE()
  set( CMAKE_CXX_FLAGS "-g -W -Wall -std=c++11 -DDEBUG -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__ -Wno-unused-variable")
ENDIF()

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O2")
set( CUDA_NVCC_FLAGS "-Wno-deprecated-gpu-targets --expt-relaxed-constexpr -arch=sm_30") # --resource-usage")

include_directories( ${INCLUDE_DIRS})

set(CMAKE_BUILD_TYPE Debug)

cuda_add_executable( main ${CUDA_SOURCES} ${CPP_SOURCES} )
```
